### ISSUE TITLE
[Feature] 랭킹 포인트 시스템 구현

### ISSUE THREAD

**Issue by mingeun0507** [Manna-voca/zenga-backend#75]
## 📑 작업 사항
- 랭킹 포인트 시스템 구현

## To-do

- [ ] 랭킹 포인트 도메인 구현
- [ ] DENSE_RANK 사용하여 랭킹 조회하는 쿼리 및 API 구현
- [ ] 기존 포인트 획득 시스템에 랭킹 포인트 얻는 로직 추가
