### ISSUE TITLE
[Fix] 칭찬 셔플 횟수 동적으로 제공 및 자잘한 요구사항 수정

### ISSUE THREAD

**Issue by 99winnmin** [Manna-voca/zenga-backend#78]
## 📑 작업 사항

<img width="931" alt="image" src="https://github.com/Manna-voca/zenga-backend/assets/44975402/90e818e9-cdee-422d-9331-288096cef63c">

- 위 요구사항에 따른 칭찬 셔플 횟수 동적 제어

## To-do

- [ ] PraiseCreateUseCase.getCurrentTodoPraiseAndMemberList() 메서드 내부에 칭찬 후보자 생성되는 로직 변경
- [ ] PATCH /praise/open API Response 수정
- [ ] Member Entity 의 LevelType Enum 타입에 ADMIN 추가

## ETC

- 칭찬 오픈 시 response 값에 칭찬한 사람 이름, 프로필 이미지 추가
- Member LevelType 에 ADMIN 추가
